---
# apt update
- name: Run the equivalent of "apt-get update"
  apt:
     update_cache: yes
  become: true

# Docker install
- name: Docker install
  shell: "apt update && apt install -y curl && curl https://get.docker.com -o install.sh && sh install.sh"
  become: true

# Add user student to run Docker
- name: Add user "student" to run Docker
  shell: "chown student:docker /var/run/docker.sock"
  become: true

# Docker remove config
- name: Docker cremove config
  ansible.builtin.file:
    path: /etc/docker/daemon.json
    state: absent
  become: true

# Docker config set mirrors
- name: Docker config set mirrors
  copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {"registry-mirrors": ["https://mirror.gcr.io", "https://daocloud.io", "https://c.163.com/", "https://registry.docker-cn.com"]}
  become: true

# Restart Docker on host
- name: Restart Docker service
  shell: "service docker restart"
  become: true
