---
# apt update
- name: Run the equivalent of "apt-get update"
  apt:
     update_cache: yes
  become: true

# Docker install
- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  become: true

# Add user student to run Docker
- name: Add user "student" to run Docker
  shell: "chown student:docker /var/run/docker.sock"
  become: true

# Restart Docker on host
- name: Restart Docker service
  shell: "service docker restart"
  become: true
