---
# apt update
- name: Run the equivalent of "apt-get update"
  apt:
     update_cache: yes
  become: true

# Убеждаемся, что служба Docker запущена и добавлена в автозагрузку
- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
  become: true

# Вместо изменения прав на .sock файл вручную, добавляем пользователя в группу docker
- name: Add user "student" to docker group
  user:
    name: student
    groups: docker
    append: yes
  become: true

# Docker remove config
- name: Docker cremove config
  ansible.builtin.file:
    path: /etc/docker/daemon.json
    state: absent
  become: true

# Docker config set mirrors
- name: Docker config set mirrors
  copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {"registry-mirrors": ["https://mirror.gcr.io", "https://daocloud.io", "https://c.163.com/", "https://registry.docker-cn.com"]}
  become: true

# Restart Docker on host
- name: Restart Docker service
  shell: "service docker restart"
  become: true
